// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfvP2aIZGRoNOFJNL6FwUIct8gMw0_dqE',
    appId: '1:245216343621:web:6fcd2e9a392274207ad52c',
    messagingSenderId: '245216343621',
    projectId: 'leap-e2b88',
    authDomain: 'leap-e2b88.firebaseapp.com',
    storageBucket: 'leap-e2b88.appspot.com',
    measurementId: 'G-H3YR7V9343',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvqpUiMpMb68esUozF2wgPM5p26iGeDCg',
    appId: '1:245216343621:android:00b61d12fcd519bd7ad52c',
    messagingSenderId: '245216343621',
    projectId: 'leap-e2b88',
    storageBucket: 'leap-e2b88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4p9-JCjbYlIe92_yNAKYihOqCximlmzI',
    appId: '1:245216343621:ios:ef8949f418d2881f7ad52c',
    messagingSenderId: '245216343621',
    projectId: 'leap-e2b88',
    storageBucket: 'leap-e2b88.appspot.com',
    iosBundleId: 'com.example.revisit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4p9-JCjbYlIe92_yNAKYihOqCximlmzI',
    appId: '1:245216343621:ios:ef8949f418d2881f7ad52c',
    messagingSenderId: '245216343621',
    projectId: 'leap-e2b88',
    storageBucket: 'leap-e2b88.appspot.com',
    iosBundleId: 'com.example.revisit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfvP2aIZGRoNOFJNL6FwUIct8gMw0_dqE',
    appId: '1:245216343621:web:8a736dc95134c5247ad52c',
    messagingSenderId: '245216343621',
    projectId: 'leap-e2b88',
    authDomain: 'leap-e2b88.firebaseapp.com',
    storageBucket: 'leap-e2b88.appspot.com',
    measurementId: 'G-4HFJMFBLXS',
  );

}